#!/usr/bin/python
import hashlib
import sys
import urllib2
import urllib
server = 'http://hashcache.provebit.org/'
def print_help():
    """ Print usage instructions for the command-line library. """
    print("Usage: ./hashcache [command]")
    print("./hashcache help [command name] - display extended command information.\n")
    print("Available commands:")
    print("\topenwindow")
    print("\tclosewindow")
    print("\thashdocument [file path]")
    print("\tadddocument [document hash]")
    print("\tviewwindow [windowID]")

def print_command_help(command):
    """ Display extended help information for CLI command
        :param command: HashCache command name"""
    COMMANDS = \
        { "openwindow": \
            "Opens a collection window on the server, allowing documents to be uploaded.", \
          "closewindow": \
            "Closes a collection window on the server, printing the collectionID for the closed collection window", \
          "hashdocument": \
            "Provide a document hash for the input file", \
          "viewwindow": \
            "Display all known document hashes for the associated collection window.", \
        }
    if command in COMMANDS:
        print (COMMANDS[command])
    else:
        print ("Unknown command!")
        print_help()

def openwindow():
	openRequest = urllib2.Request(server + "api/window/open")
	openResponse = urllib2.urlopen(openRequest)
	print(openResponse.read())   

def viewwindow(windowID):
	viewRequest = urllib2.Request(server + "api/window/id/" + windowID)
	viewResponse = urllib2.urlopen(viewRequest)
	print(viewResponse.read())   



def closewindow():
	closeRequest = urllib2.Request(server + "api/window/close")
	closeResponse = urllib2.urlopen(closeRequest)
	print(closeResponse.read())   


def hashdocument(fileName):
    print hashlib.sha256(open(fileName, 'rb').read()).hexdigest()

def adddocument(documentHash):
	addRequest = urllib2.Request(server + "api/hashes")
	opener = urllib2.build_opener(urllib2.HTTPHandler())
	hashData = urllib.urlencode({'hash' : documentHash})
	content = opener.open(server + "api/hashes", data=hashData).read()
	print("Added Document Hash to current collection window")



def process_command(command):
    """ Process a command-line command and execute the 
        resulting FreeJournal action
        :param command: The command to be executed, as a sys arg array
    """
    if len(sys.argv) < 2:
        print_help()
        return
    command = sys.argv[1].lower()
    if command == 'help':
        if (len(sys.argv) == 3):
            print_command_help(sys.argv[2])
        else:
            print_help()
    elif command == 'openwindow':
        openwindow()
    elif command == 'closewindow':
        closewindow()
    elif command == 'viewwindow':
        if (len(sys.argv)==3):
            viewwindow(sys.argv[2])
        else:
            print_help()
    elif command == 'hashdocument':
        if(len(sys.argv)==3):
            hashdocument(sys.argv[2])
        else:
            print_help()
    elif command == 'adddocument':
        if(len(sys.argv)==3):
            adddocument(sys.argv[2])
        else:
            print_help()
    else:
        print_help()

if __name__ == '__main__':
    process_command(sys.argv)
