#!/usr/bin/python
import hashlib
import sys

def print_help():
    """ Print usage instructions for the command-line library. """
    print("Usage: ./hashcache [command]")
    print("./hashcache help [command name] - display extended command information.\n")
    print("Available commands:")
    print("\topenwindow")
    print("\tclosewindow")
    print("\thashdocument [file path]")
    print("\tadddocument [document hash]")
    print("\tshowcollection [collectionID]")

def print_command_help(command):
    """ Display extended help information for CLI command
        :param command: FreeJournal command name"""
    COMMANDS = \
        { "openwindow": \
            "Opens a collection window on the server, allowing documents to be uploaded.", \
          "closewindow": \
            "Closes a collection window on the server, printing the collectionID for the closed collection window", \
          "hashdocument": \
            "Provide a document hash for the input file", \
          "showcollection": \
            "Display all known document hashes for the associated collection window.", \
        }
    if command in COMMANDS:
        print (COMMANDS[command])
    else:
        print ("Unknown command!")
        print_help()

def openwindow():
    print("Collection Window Opened")

def closewindow():
    print("Collection Window Closed")

def hashdocument(fileName):
    print hashlib.sha256(open(fileName, 'rb').read()).hexdigest()

def adddocument(documentHash):
    print("Added Document Hash to current collection window")



def process_command(command):
    """ Process a command-line command and execute the 
        resulting FreeJournal action
        :param command: The command to be executed, as a sys arg array
    """
    if len(sys.argv) < 2:
        print_help()
        return
    command = sys.argv[1].lower()
    if command == 'help':
        if (len(sys.argv) == 3):
            print_command_help(sys.argv[2])
        else:
            print_help()
    elif command == 'openwindow':
        openwindow()
    elif command == 'closewindow':
        closewindow()
    elif command == 'showcollection':
        if (len(sys.argv)==3):
            showcollection(sys.argv[2])
        else:
            print_help()
    elif command == 'hashdocument':
        if(len(sys.argv)==3):
            hashdocument(sys.argv[2])
        else:
            print_help()
    else:
        print_help()

if __name__ == '__main__':
    process_command(sys.argv)
